#
# Development docker-compose file. For production, see production repository #3.
#

services:
  registry-proxy:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgresql
    networks:
      - registry-proxy

  postgresql:
    image: docker.io/bitnami/postgresql:17
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    env_file:
      - .env
    networks:
      - registry-proxy

volumes:
  postgresql_data:
    driver: local

networks:
  registry-proxy:
    driver: bridge