name: Build and Publish Docker Image

on:
  release:
    types:
      - published

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version
        id: extract_version
        run: |
          VERSION=${{ github.event.release.tag_name }}
          VERSION_CLEANED=$(echo "$VERSION" | sed 's/-sws$//')
          echo "VERSION=$VERSION_CLEANED" >> $GITHUB_ENV
          echo "Version after cleaning: $VERSION_CLEANED"

      - name: Set up QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push multi-arch Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/dominic-r/docker-registry-proxy:${VERSION} \
            --push .
